"$schema": "http://json-schema.org/draft-07/schema#"
definitions:
  conv:
    type: object
    additionalProperties: false
    properties:
      filters:
        description: "trainable parameter filters in the conv2d layer"
        type: object
        properties:
          dtype:
            type: string
          initializer:
            type: object
          shape:
            description: "the shape of the trainable paramter"
            type: object
            additionalProperties: false
            properties:
              kernel_size_w:
                type: integer
              kernel_size_h:
                type: integer
              input_shape:
                type: string
                enum: ["channels"]
              n_filters:
                type: integer
      padding:
        type: string
        enum: ["VALID", "SAME"]
      strides:
        type: array
        minItems: 2
        maxItems: 2
      dilation:
        description: "dilation: currently not in use"
        type: integer
