data_block:
  - type: data
    dtype: float32
    hyperparams:
      shape:
        batch_size: null
        height: 32
        width: 32
        channels: 3
    name: input_data

  - type: label
    dtype: int64
    hyperparams:
      shape:
        batch_size: null
        dim: 10
    name: labels

model_block:
  - type: conv
    hyperparams:
      strides:
        - 1
        - 1
      filters:
        shape:
          n_filters:
            16
    inputs: data_block/input_data

  - type: batch_normalize

  - type: relu

  - type: resnet_16

  - type: resnet_32_short_cut

  - type: resnet_32

  - type: resnet_64_short_cut
  - type: resnet_64

    name: features

  - type: max_pool2d
  - type: flatten

  - type: dense
  - type: dropout
    name: d_1

loss_block:
  - type:
      cross_entropy
    inputs:
      - labels
      - d_1
    name: losses


optimizer_block:
  - type: adam
    inputs: loss_block/losses
    name: solver
    hyperparams:
      learning_rate:
        0.1


  # - type: inference
  #   inputs:
  #     - labels
  #     - d_1
  #   name: inference_1
