data_block:
  - type: data
    hyperparams:
      shape:
        batch_size: null
        height: 32
        width: 32
        channels: 3
    name: input_data

model_block:

  - type: conv
    inputs:
      - data_block/input_data
    hyperparams:
      filters:
        shape:
          n_filters: 4
  - type: max_pool2d
  - type: max_pool2d
  - type: flatten
    name: output

loss_block:
  - type: conv
    trainable: False
    hyperparams:
      filters:
        shape:
          n_filters:
            16
    inputs:
      - data_block/input_data
  - type:
      relu
    name: "reluu"
  - type:
      dropout
  - type:
      batch_normalize
    trainable: False

  - type: conv
    trainable: False
    hyperparams:
      padding: VALID
  # - type: max_pool2d
  - type: conv
    trainable: False
    hyperparams:
      padding: VALID
  - type: flatten
    name: feature
  - type:
      mse
    inputs:
      - feature
      - model_block/output
    name: cross_0

  - type:
      regularizer_l2
    inputs:
      - connect_to:
          range: :-1
          types:
            dense: weights
            conv: filters
          scope: all # default: all
    name: regularizer

  - type: add
    inputs:
      - cross_0
      - regularizer
    name: losses

optimizer_block:
  - type: adam
    inputs: loss_block/losses
    name: solver
    hyperparams:
      learning_rate:
        0.0001
