params_network:
  - type: data
    hyperparams:
      shape:
        batch_size: null
        height: 32
        width: 32
        channels: 3
    name: input_data

  - type: label
    dtype: int64
    hyperparams:
      shape:
        batch_size: null
        dim: 10
    name: labels

  - type: conv
    hyperparams:
      filters:
        shape:
          n_filters:
            16
    input_component: input_data
  - type:
      relu
    name: "reluu"
  - type:
      dropout
  - type:
      batch_normalize

  - type: conv
    hyperparams:
      filters:
        shape:
          n_filters:
            16
      padding: SAME
      strides: [1,1]
  # - type: max_pool2d
  - type: conv
    hyperparams:
      filters:
        shape:
          n_filters: 16
      padding: SAME
      strides: [1,1]
  - type: flatten
  - type: dense
  - type: softmax
    name: d_1
# losses:
  - type:
      cross_entropy
    name: losses

# solvers:
  - type: adam
    input_component: losses
    name: solver
    hyperparams:
      learning_rate:
        0.1
