data_block:
  - type: data
    hyperparams:
      shape:
        batch_size: null
        height: 32
        width: 32
        channels: 3
    name: input_data

  - type: label
    dtype: int64
    hyperparams:
      shape:
        batch_size: null
        dim: 10
    name: labels

model_block:
  - type: conv
    hyperparams:
      filters:
        shape:
          n_filters:
            16
    inputs: data_block/input_data
  - type:
      relu
  - type:
      dropout
  - type:
      batch_normalize

  - type: resnet_16
  - type: flatten
  - type: dense
  - type: softmax
  - type: sigmoid
    name: d_1

loss_block:
  - type:
      cross_entropy
    inputs:
      - data_block/labels
      - model_block/d_1
    name: losses

optimizer_block:
  - type: adam
    inputs: loss_block/losses
    name: solver
    hyperparams:
      learning_rate:
        0.0001
