params_network:
  - type: data
    hyperparams:
      shape:
        batch_size: null
        height: 32
        width: 32
        channels: 3
    name: input_data

  - type: label
    dtype: int64
    hyperparams:
      shape:
        batch_size: null
        dim: 10
    name: labels

  - type: conv
    hyperparams:
      filters:
        shape:
          n_filters:
            16
    inputs: input_data
  - type:
      relu
  - type:
      dropout
  - type:
      batch_normalize

  - type: resnet_16
  - type: flatten
  - type: dense
  - type: softmax
    name: d_1
  - type: sigmoid
# losses:
  - type:
      cross_entropy
    inputs:
      - labels
      - d_1
    name: losses

# solvers:
  - type: adam
    inputs: losses
    name: solver
    hyperparams:
      learning_rate:
        0.1
